In [ ]:
#Means 

[-1.0868241607441758,
 -1.0547327320000592,
 -1.016991296777501,
 -0.9850300306259748,
 -0.9550637747222407,
 -0.9219496175741501,
 -0.8918558154776248,
 -0.8640471493153424,
 -0.8402692461570486,
 -0.8127401410758444]

#Standard Deviations (Divide by sqrt(100) to get errors on mean)

[0.01345095659706539,
 0.01307470304205118,
 0.0172569980985815,
 0.015873630825518865,
 0.01736988334553417,
 0.02041070288500645,
 0.020119864394138168,
 0.017420698374431998,
 0.01880486251910809,
 0.0184854385676588]

#Parameters of 5 degree fit, factoring in standard deviation (i.e. statistical uncertainties) of the points 
#--using np.polyfit; coeff organized as highest power first and on

[-3.26256462e-07  2.00283564e-05 -3.61793099e-04  2.01552500e-03
  2.98038921e-02 -1.11862337e+00]

# Zero point extrapolation by 5th degree fit 

## Extrapolated 0 noise energy 
-1.118623371491511

## Monte Carlo Uncertainty
0.19637905723682356

## Covariance Uncertainty
0.010500511790350091

#Just for comparison, exact energy is 
-1.137283834488501

In [17]:
import numpy as np
def RichardsonExtrap(energies): 
    """
    Input: An array of energies scaled with different stretch factors--normal integer multiples only --eg 1,2,3,4..
    Output: Zero Error extrapolated answer
    """
    n = len(energies)
    scales = [2*i+1 for i in range(n)]
    
    #setting up all equations 
    equations = []
    for eq_num in scales: 
        equation = []
        if eq_num == 1: 
            for i in range(n): 
                equation.append(1)
            equations = [equation]
        else: 
            for term_num in scales: 
                term = term_num**(int(eq_num/2))
                equation.append(term)
            equations = np.append(equations, [equation], axis = 0)
    print(equations)
    
    #Now filling up equals to matrix 
    equals_to = [1]
    for i in range(1, len(scales)): 
        equals_to.append(0)
    print(equals_to)
    
    #solving the system
    coeff = np.linalg.solve(equations, equals_to)
    #print(coeff)
    
    #Combine coeff with energies to get zero noise result 
    result = np.dot(coeff, energies)
    return result

In [18]:
energies = [1, 1,1,1,1]
RichardsonExtrap(energies)

[[   1    1    1    1    1]
 [   1    3    5    7    9]
 [   1    9   25   49   81]
 [   1   27  125  343  729]
 [   1   81  625 2401 6561]]
[1, 0, 0, 0, 0]


1.0000000000000002